[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo_mysql', 'php82Extensions.iconv']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'php -S 0.0.0.0:$PORT app.php'

[variables]
NIXPACKS_PHP_EXTENSIONS = 'pdo_mysql,iconv'